### PR TITLE
Travis fix branch

### PR DESCRIPTION
**Pull request by ndavis6**

### CODE REVIEW

**Comment by marcparewatttime** [comment]
The build never passed but this got merged? I've seen this bug before and fixed it a different way...would need to look into it further to remember exactly how though.

**Comment by eayoungs** [comment]
Doesn't look like it's used much:
`Searching 115 files for "libfaketime" (regex)

/Users/eayoungs/repo/Code/Work/pyiso/requirements.txt:
   16: libfaketime

/Users/eayoungs/repo/Code/Work/pyiso/tests/test_load.py:
    9: import libfaketime
   10: libfaketime.reexec_if_needed()
  311: #     @libfaketime.fake_time('2016-05-20 14:45')

4 matches across 2 files`

**Comment by ndavis6** [comment]
Hi @eayongs,  Libfaketime is part of a project to mock more of the tests and achieve more consistent test suite behavior.  Ideally we would like to mock all of the tests, but we haven't gotten there yet.  It looks like libfaketime hasn't been updated in several years, it might be worthwhile to move to freezegun (https://github.com/spulec/freezegun).

**Comment by eayoungs** [comment]
Thanks, @ndavis6 ; just trying to sort out what the cause of the build failure is. It looks like all the open PRs are failing as well, so it seems to me that it's likely the cause is upstream of recent changes.

**Comment by eayoungs** [comment]
I tried the example queries in the following document. They all seem to return 404s both in the browser and in my REST Client (Postman).

** wonder if they changed the API without announcing it?**

http://www.caiso.com/Documents/OASIS-InterfaceSpecification_v4_2_6Clean_Independent2015Release.pdf

**Pull request merged**
