### PR TITLE
Added get_lmp_loc() method to caiso for retrieving geographic locations of lmp nodes.

### PR DESCRIPTION
**Pull request by dzimmanck**
I added a simple method to caiso that grabs LMP location data from CAISO's online interactive price map.  This can be used to generate geo maps from the LMP data pulled using pyiso.

### CODE REVIEW

**Comment by aschn** [comment]
This looks great! Can you add these lines to the bottom of `tests.test_caiso`? Then we'll be good to merge.

```
    def test_lmp_loc(self):
        c = client_factory('CAISO')
        loc_data = c.get_lmp_loc()

        # one entry for each node
        # expected count is 4238
        self.assertGreater(len(loc_data), 4000)

        # check keys
        self.assertItemsEqual(loc_data[0].keys(),
                              ['node_id', 'latitude', 'longitude', 'area'])
```

**Comment by dandxy89** [comment]
Fails due to Authorization

**Comment by aschn** [comment]
Hi @dandxy89 ! Did you try adding environment variables for these accounts when you run the tests? http://pyiso.readthedocs.org/en/latest/configuration.html#accounts

**Comment by dandxy89** [comment]
The variables are only for New England ISO and European ISO. Not why they would help? :S

**Comment by ndavis6** [comment]
@dandxy89 Did you ever figure out the environment variable problem?

**Comment by dandxy89** [comment]
Not sure anymore, this was almost a year ago I was working on ISO consumers.

**Pull request closed without merging**
