### PR TITLE
Increment version to 0.4.0 to reflect breaking change.

### LINKED ISSUE #22: Update docs for CAISO LMP and AS
As requested by @jinhw1989 in issue #6.

### LINKED ISSUE #26: kwarg to collect additional data from CAISO lmp
`get_lmp` could be returning congestion price, etc in addition to LMP. Add a kwarg `all_data=False` that, if set to `True`, returns all the data types instead of just LMP.

### LINKED ISSUE #159: `get_lmp()` for PJM fails to retrieve data for multiple node_ids
```python
from pyiso import client_factory
import pandas as pd
pjm = client_factory('PJM')
```
each of the two node id's requested independently return the correct results, but when combined, it only returns results for the first node id.

```python
pd.DataFrame(pjm.get_lmp(start_at=datetime.strptime('2016-01-01 00 UTC', '%Y-%m-%d %H %Z'),
                         end_at=datetime.strptime('2016-01-03 00 UTC', '%Y-%m-%d %H %Z'),node_id=[40243837,32417577])).node_id.unique()
```
returns:
```
array([40243837])
```

### LINKED ISSUE #162: CAISO - .get_lmp error 502
Hello,

Attempting to run a for loop that will cycle through the months of 2016 and grab historical LMP data for a select number of nodes. I'm getting a 502 error very sporadically as the program runs, it will grab one or two node lmp data than give me the error for the next 5-6. I've noticed that as I restart the program the 502 errors are not for the same nodes so I don't believe it's a problem of not having the data.

Would anyone have any thoughts on why this may happen (code below)? I thought it may have been too much for the server so I tried with various sleep options, but it hasn't helped.

```
count = 0
caiso = client_factory("CAISO", timeout_seconds=360)

year = 2016

for start_month in range(1,6):
	end_month = start_month + 1
	start = str(start_month) + "/" + str(year)
	end = str(end_month) + "/"+str(year)
	date1 = datetime.strptime(start, "%m/%Y")
	date2 = datetime.strptime(end, "%m/%Y")
	month_name = datetime.strftime(date1,"%b"+"_"+"%Y")
	for node in nodes:
		sleep(65)
		try:
			count += 1
			data = caiso.get_lmp(start_at=date1, end_at=date2, node_id=node)
			df = pd.DataFrame(data)
			df.to_csv("LMP_"+node+month_name+".csv")
			print(count, node, date1)
		except:
			pass
			print("COULD NOT GRAB DATA FOR"+node+"on"+date1)
```

### PR DESCRIPTION
**Pull request by r24mille**
Commits 22323c6, 79464e1, and fa7524c remove the `get_lmp(...)` method from BaseClient and increment the version to 0.3.20. This is a backwards-incompatible change which we should give a greater indication of via the package version number.

The industry conventions of semantic versioning (http://semver.org) suggest that the first version number position should be incremented for backward-incompatible API changes. That would mean pyiso should be incremented to 1.0.0. That feels a bit odd, so I suggest that we at least increment the version number to 0.4.0,which is reflected in this commit.

Also, we should clean out old pull requests and issues that reference LMP, since we no longer wish to include that functionality. We can do that using [GitHub's issue keywords](https://help.github.com/articles/closing-issues-using-keywords/) to close those issues, since they will not be fixed: closes #26, closes #22, closes #162, and closes #159. It would also close these pull requests: closes #52 and closes #106.

### CODE REVIEW

**Comment by ajdonnison** [comment]
It seems that doing it with the command line allows you to get the commits in but it doesn't close the PR.  So if you don't see an issue, can we close this (as the commits are now in master)?  Or at least rebase off master and try again?

**Comment by r24mille** [comment]
Well, merging in the pull request via GitHub's client interface allows the issue keywords I set up to trigger. Just closing the pull request won't trigger them.

What's the rationale behind squash commits via command line rather than working with community contributions (like this and others) through GitHub's web interface or client?

**Comment by ajdonnison** [comment]
I'm more used to a rebase workflow, and in this case simply tried that to see if I could get past the conflict.  It was only partially successful as I forgot to add a commit message to close this - the perils of doing git before coffee, I guess.  I prefer squash and a combined commit message than individual commits simply to keep the history cleaner, but I am not wedded to one approach or another.  Basically anything that works and doesn't cause contributors to get frustrated or confused is fine by me.  I don't mind if it is only me being frustrated and confused :)

**Comment by r24mille** [comment]
OK, 0a550dc corrects the README to reflect the current state of things. It should also conveniently correct the merge button issues we're currently experiencing.

Regarding the GitHub Flow merge vs. rebase workflow... I've never worked in a rebase workflow so I can't speak to its strengths. I've only ever worked with a gitflow workflow and a GitHub Flow workflow. If I can speak in favour of GitHub Flow for a few reasons:
- Community interactions via pull requests gives signs-of-life to the repository. That's something I look for when considering which projects to commit to. As an example, with PR #169 I intentionally branched off of @emunsing's work so that he could get credit for uncovering the initial problem in PR #112. I was basically just putting polish on his work from our discussion in PR #112. The rebase trashed his commit in the history and made it look like its my contribution (which it really wasn't).
- As a contributor, I'm actually running 4-5 parallel development branches https://github.com/r24mille/pyiso/branches Since the commit IDs change, I can't tell which of my branches have been merged in easily or not. I've been having to go look at WattTime's closed PRs, match it to the branch name I gave, and manually delete my branches. Makes things a bit more difficult to track as a contributor.
- Some people contribute publicly on GitHub to improve their resume or for other vanity reasons (and that's OK). My ~100 commits of regular contributions to WattTime did get squashed into 4 commits. I'm trying not to be too sensitive to it, but I did weep a single, very vain tear on the inside :p

**Comment by ajdonnison** [comment]
These are all extremely good points you make, and I take them to heart.  Using the web interface or not shouldn't make any difference, the main problem was that I chose to squash the commits, which, as you rightly point out, is not fair on you or other contributors who expect to see all of their commits in the history.  In general squash and rebase work best when it is done by the contributor, not some interfering busybody who thinks they know best (and yes, I'm referring to myself here). 

From here on in I'll make sure I don't succumb to the temptation to follow old habits and instead follow a more community-minded approach.  I can only offer my sincerest apologies for the confusion, and for the single tear, Vain or not it is not something I want to see in people like yourself who have done so much for the project.

**Pull request merged**
