### PR TITLE
small readme change - Link the vocab term "ISO" to its definition

### PR DESCRIPTION
**Pull request by hangtwenty**
(making clear immediately that it is not to be confused with ISO in the sense of [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601))

### CODE REVIEW

**Comment by hangtwenty** [comment]
On second thought I don't think this is the best link, I was a bit hasty in submitting the PR (apologies). But it could be good to link to _some_ good resource there.

**Comment by ndavis6** [comment]
Not at all, we appreciate the PR, especially on documentation.  That isn't a bad link at all, but maybe https://www.epsa.org/industry/primer/?fa=rto is a better link?  Does that link make sense to you?

**Comment by hangtwenty** [comment]
That makes _perfect_ sense 😄

**Comment by ndavis6** [comment]
Great, do you want to resubmit the PR with that?

**Pull request merged**
